### ISSUE TITLE
Weather not syncing to server

### ISSUE THREAD

**Issue by Maloonkey** [GeyserMC/Geyser-Fabric#51] opened 2022-05-20 05:08 UTC
1.18.2 Geyser-Fabric; Bedrock client isn't syncing weather after Clear -> Rain, it stays stuck raining until a reconnect to the server.

Server modlist:
```
Geyser-Fabric-2.0.3-SNAPSHOT.jar
c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar
fabric-api-0.51.1+1.18.2.jar
fabrictailor-1.8.1.jar
ferritecore-4.2.1-fabric.jar
graves-2.0.0+1.18.2.jar
krypton-0.1.9.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.18.2-0.7.9.jar
servercore-1.2.9-1.18.2.jar
starlight-1.0.2+fabric.89b8d9f.jar
vmp-fabric-mc1.18.2-0.2.0+beta.3.17-all.jar
```

**Comment by Konicai** [comment] 2022-05-20 14:00
Duplicate of https://github.com/GeyserMC/Geyser/issues/2499 and/or https://github.com/GeyserMC/Geyser/issues/2588

**Closed by Konicai** 2022-05-20 14:00 UTC
