### ISSUE TITLE
the latest geyser fabric 1.40 load floodgate fabric will cause the server to crash in minecraft 1.17.1

### ISSUE THREAD

**Issue by a1637850680** [GeyserMC/Geyser-Fabric#20] opened 2021-07-11 01:08 UTC
log until

[21:37:48] [main/INFO]: Loading for game Minecraft 1.17.1
[21:37:49] [main/INFO]: [FabricLoader] Loading 66 mods:
	- adventure-platform-fabric@4.1.0-SNAPSHOT
	- carpet@1.4.43
	- cloud@1.5.0-SNAPSHOT
	- cloud_commandframework_cloud-brigadier_@1.5.0-SNAPSHOT
	- cloud_commandframework_cloud-core_@1.5.0-SNAPSHOT
	- cloud_commandframework_cloud-services_@1.5.0-SNAPSHOT
	- fabric@0.36.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d013
	- fabric-biome-api-v1@3.1.11+c345aea813
	- fabric-blockrenderlayer-v1@1.1.5+a02b446313
	- fabric-command-api-v1@1.1.2+6cefd57713
	- fabric-commands-v0@0.2.2+92519afa13
	- fabric-containers-v0@0.1.12+a02b446313
	- fabric-content-registries-v0@0.2.2+a02b446313
	- fabric-crash-report-info-v1@0.1.5+be9da31013
	- fabric-dimensions-v1@2.0.11+6cefd57713
	- fabric-entity-events-v1@1.1.0+a02b446313
	- fabric-events-interaction-v0@0.4.9+a722d8c013
	- fabric-events-lifecycle-v0@0.2.1+92519afa13
	- fabric-game-rule-api-v1@1.0.7+6cefd57713
	- fabric-item-api-v1@1.2.4+a02b446313
	- fabric-item-groups-v0@0.2.10+b7ab612113
	- fabric-key-binding-api-v1@1.0.4+a02b446313
	- fabric-keybindings-v0@0.2.2+36b77c3e13
	- fabric-lifecycle-events-v1@1.4.4+a02b446313
	- fabric-loot-tables-v1@1.0.4+a02b446313
	- fabric-mining-levels-v0@0.1.3+92519afa13
	- fabric-models-v0@0.3.0+a02b446313
	- fabric-networking-api-v1@1.0.12+6cefd57713
	- fabric-networking-blockentity-v0@0.2.11+a02b446313
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab612113
	- fabric-object-builders-v0@0.7.3+a02b446313
	- fabric-particles-v1@0.2.4+a02b446313
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee13
	- fabric-renderer-api-v1@0.4.4+5f02c96913
	- fabric-renderer-indigo@0.4.8+a02b446313
	- fabric-renderer-registries-v1@3.2.0+a02b446313
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446313
	- fabric-rendering-v0@1.1.2+92519afa13
	- fabric-rendering-v1@1.6.0+a02b446313
	- fabric-resource-loader-v0@0.4.7+b7ab612113
	- fabric-screen-api-v1@1.0.4+155f865c13
	- fabric-screen-handler-api-v1@1.1.8+a02b446313
	- fabric-structure-api-v1@1.1.12+6cefd57713
	- fabric-tag-extensions-v0@1.1.4+a02b446313
	- fabric-textures-v0@1.0.6+a02b446313
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612113
	- fabricloader@0.11.6
	- floodgate@2.0-SNAPSHOT
	- geyser-fabric@1.4.0-SNAPSHOT
	- io_leangen_geantyref_geantyref@1.3.11
	- java@16
	- lithium@0.7.3
	- minecraft@1.17.1
	- net_kyori_adventure-api@4.8.1
	- net_kyori_adventure-key@4.8.1
	- net_kyori_adventure-platform-api@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-feature-pagination@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-serializer-gson@4.8.1
	- net_kyori_adventure-text-serializer-plain@4.8.1
	- net_kyori_examination-api@1.1.0
	- net_kyori_examination-string@1.1.0
[21:37:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/usr/games/Geyser-server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[21:37:49] [main/INFO]: Compatibility level set to JAVA_16
[21:37:49] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[21:37:49] [main/WARN]: @Mixin target net/minecraft/class_3218$class_5526 is public in fabric-lifecycle-events-v1.mixins.json:ServerWorldEntityLoaderMixin and should be specified in value
[21:37:49] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[21:37:49] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[21:37:54] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[21:37:57] [main/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.330 ms
[21:37:57] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:37:57] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:37:57] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:37:57] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:37:57] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:37:57] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:37:57] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[21:37:59] [Worker-Main-4/INFO]: Loaded 7 recipes
[21:37:59] [Worker-Main-4/INFO]: Loaded 1137 advancements
[21:38:01] [Server thread/INFO]: Starting minecraft server version 1.17.1
[21:38:01] [Server thread/INFO]: Loading properties
[21:38:01] [Server thread/INFO]: Default game type: SURVIVAL
[21:38:01] [Server thread/INFO]: Generating keypair
[21:38:01] [Server thread/INFO]: Starting Minecraft server on *:11666
[21:38:01] [Server thread/INFO]: Using default channel type
[21:38:01] [Server thread/INFO]: Preparing level "world"
[21:38:01] [Server thread/INFO]: [CM]: loaded setting ctrlQCraftingFix as true from carpet.conf
[21:38:02] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:38:02] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[21:38:02] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[21:38:03] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[21:38:03] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[21:38:04] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[21:38:04] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[21:38:05] [Worker-Main-6/INFO]: Preparing spawn area: 9%
[21:38:05] [Worker-Main-4/INFO]: Preparing spawn area: 38%
[21:38:06] [Worker-Main-6/INFO]: Preparing spawn area: 74%
[21:38:08] [Server thread/INFO]: Time elapsed: 6161 ms
[21:38:08] [Server thread/INFO]: Done (6.463s)! For help, type "help"
[21:38:08] [Server thread/INFO]: Auto-loaded Floodgate key
[21:38:08] [Server thread/INFO]: ******************************************
[21:38:08] [Server thread/INFO]: 
[21:38:08] [Server thread/INFO]: Loading Geyser version 1.4.0-SNAPSHOT (git-master-334e4fb)
[21:38:08] [Server thread/INFO]: 
[21:38:08] [Server thread/INFO]: ******************************************
[21:38:26] [Server thread/INFO]: Loaded Floodgate key!
[21:38:26] [Network Listener - #1/INFO]: Started Geyser on 0.0.0.0:11667
[21:38:26] [Server thread/INFO]: Done (18.359s)! Run /geyser help for help!
[21:38:26] [Server thread/INFO]: floodgate.core.finish 36
[21:38:26] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 18406ms or 368 ticks behind
[21:39:04] [Network Listener - #1/INFO]: /171.113.80.157:29971 tried to connect!
[21:39:04] [Network Listener - #1/INFO]: /171.113.80.157:29971 tried to connect!
[21:39:04] [Network Listener - #1/INFO]: Bedrock user with ip: /171.113.80.157 has disconnected for reason CLOSED_BY_REMOTE_PEER
[21:39:32] [User Authenticator #1/INFO]: UUID of player LakeRings is e968a077-77e9-4085-aa44-8e35888881f8
[21:39:32] [Server thread/INFO]: LakeRings[/123.180.200.170:26428] logged in with entity id 189 at (257.34737658986217, 39.0, 193.85020656823326)
[21:39:32] [Server thread/INFO]: LakeRings joined the game
[21:40:03] [Network Listener - #1/INFO]: /223.198.141.166:16734 tried to connect!
[21:40:04] [Network Listener - #1/INFO]: Player connected with username zcg11233
[21:40:11] [Network Listener - #1/INFO]: Attempting to login using floodgate mode... authentication will be encrypted.
[21:40:11] [nioEventLoopGroup-2-1/INFO]: zcg11233 (logged in as: zcg11233) has connected to remote java server on address 127.0.0.1
[21:40:11] [nioEventLoopGroup-2-1/WARN]: We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[21:40:11] [Netty Server IO #2/WARN]: We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[21:40:11] [nioEventLoopGroup-2-1/INFO]: Registering bedrock skin for .zcg11233 (00000000-0000-0000-0009-01f0feb7ecea)
[21:40:11] [Server thread/INFO]: .zcg11233[/127.0.0.1:35487] logged in with entity id 398 at (44.030113, 75.0, 345.5104)
[21:40:11] [Server thread/INFO]: floodgate.ingame.login_name .zcg11233, 00000000-0000-0000-0009-01f0feb7ecea
[21:40:11] [Server thread/INFO]: .zcg11233 joined the game
[21:40:26] [Netty Server IO #2/INFO]: floodgate.ingame.disconnect_name .zcg11233
[21:40:26] [nioEventLoopGroup-2-1/INFO]: zcg11233 has disconnected from remote Java server on address 127.0.0.1 because of 连接超时
[21:40:26] [Server thread/INFO]: .zcg11233 lost connection: Timed out
[21:40:26] [Server thread/INFO]: .zcg11233 left the game
[21:40:26] [Network Listener - #1/INFO]: Bedrock user with ip: /223.198.141.166 has disconnected for reason CLOSED_BY_REMOTE_PEER
[21:41:05] [Network Listener - #1/INFO]: /223.198.141.166:16734 tried to connect!
[21:41:05] [Network Listener - #1/INFO]: Player connected with username zcg11233
[21:41:13] [Network Listener - #1/INFO]: Attempting to login using floodgate mode... authentication will be encrypted.
[21:41:13] [nioEventLoopGroup-2-2/INFO]: zcg11233 (logged in as: zcg11233) has connected to remote java server on address 127.0.0.1
[21:41:13] [nioEventLoopGroup-2-2/WARN]: We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[21:41:13] [Netty Server IO #3/WARN]: We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[21:41:13] [nioEventLoopGroup-2-2/INFO]: Registering bedrock skin for .zcg11233 (00000000-0000-0000-0009-01f0feb7ecea)
[21:41:13] [Server thread/INFO]: .zcg11233[/127.0.0.1:60323] logged in with entity id 579 at (44.030113, 75.0, 345.5104)
[21:41:13] [Server thread/INFO]: floodgate.ingame.login_name .zcg11233, 00000000-0000-0000-0009-01f0feb7ecea
[21:41:13] [Server thread/INFO]: .zcg11233 joined the game
[21:41:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_2716.<init>(int)'
	at org.geysermc.floodgate.pluginmessage.FabricSkinApplier.lambda$applySkin$0(FabricSkinApplier.java:52) ~[floodgate-fabric.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjm000$modifiedRunLoop(MinecraftServer.java:3899) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:41:14] [Server thread/ERROR]: This crash report has been saved to: /usr/games/Geyser-server/./crash-reports/crash-2021-07-09_21.41.14-server.txt
[21:41:14] [Server thread/INFO]: Shutting down Geyser.
[21:41:14] [Server thread/INFO]: Kicking 1 player(s)
[21:41:14] [Server thread/INFO]: Kicked all players!
[21:41:14] [Netty Server IO #3/INFO]: floodgate.ingame.disconnect_name .zcg11233
[21:41:14] [nioEventLoopGroup-2-2/INFO]: zcg11233 has disconnected from remote Java server on address 127.0.0.1 because of Geyser代理正在关闭
[21:41:14] [Network Listener - #1/INFO]: Bedrock user with ip: /223.198.141.166 has disconnected for reason SHUTTING_DOWN
[21:41:14] [Server thread/INFO]: Geyser shutdown successfully.
[21:41:14] [Server thread/INFO]: Stopping server
[21:41:14] [Server thread/INFO]: Saving players
[21:41:14] [Server thread/INFO]: LakeRings lost connection: Internal Exception: java.lang.StackOverflowError
[21:41:14] [Server thread/INFO]: LakeRings left the game
[21:41:14] [Server thread/INFO]: Saving worlds
[21:41:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:41:15] [WebSocketConnectReadThread-117/INFO]: The skin uploader has been closed
[21:41:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[21:41:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[21:41:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:41:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:41:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:41:18] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by a1637850680** [comment] 2021-07-11 01:11
or rather gyeser1.40 can‘t suport minecraft 1.17.1？

**Comment by DelxHQ** [comment] 2021-07-11 21:24
I also get this error.

**Comment by Konicai** [comment] 2021-07-21 02:25
Any difference if you use the latest version of Geyser and Floodgate, fabric-api `0.37.0+1.17`, and fabric loader `0.11.6` ? I couldn't reproduce it.

**Comment by Konicai** [comment] 2021-07-21 14:50
Tried again additionally with carpet@1.4.44 and lithium@0.7.3, couldn't reproduce. 
https://paste.gg/p/anonymous/4b964d14324648c9ba31af08c60ae2c3

**Comment by FarLanderCraft** [comment] 2021-07-21 16:14
I'm having exactly the same issue, is there an earlier commit to either that works? I kind of want this running as soon as possible.

**Comment by Konicai** [comment] 2021-07-21 16:16
You can try using older versions of geyser/floodgate but its not supported

If you join our Discord I can help you there faster https://discord.gg/GeyserMC

**Comment by FarLanderCraft** [comment] 2021-07-21 16:23
I'm kind of maxed out on Discord...
;-;

**Comment by DelxHQ** [comment] 2021-07-23 00:18
I'm going to take a guess that its some kind of skin that causing this issue. This error only happens for me if a certain player isn't the first person to join the server.

**Comment by tobfos2611** [comment] 2021-07-23 11:43
This issue is also happening to me.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/23/21, 11:35 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2716.<init>(int)'
	at org.geysermc.floodgate.pluginmessage.FabricSkinApplier.lambda$applySkin$0(FabricSkinApplier.java:52)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 3.10.0-1160.15.2.el7.x86_64
	Java Version: 16.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 918516936 bytes (875 MiB) / 3053453312 bytes (2912 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 66294.28
	Virtual memory used (MB): 77455.15
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1291.32
	JVM Flags: 20 total; -Xmx3072M -Xms1996M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		cloud: Cloud 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-core_: cloud-core 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-services_: cloud-services 1.5.0-SNAPSHOT
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_github_wearblackallday_javautils: JavaUtils 1b369d41cd
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_konghq_unirest-java_standalone: unirest-java 3.11.9
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		dimthread: DimensionalThreading 1.2.5
		disfabric: DisFabric 1.3.3
		eer: Erroring Entity Remover 1.0.0
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab612118
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fabrilousupdater: FabrilousUpdater 2.3
		ferritecore: FerriteCore 3.0.1
		floodgate: Floodgate-Fabric 2.0-SNAPSHOT
		geyser-fabric: Geyser-Fabric 1.4.0-SNAPSHOT
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.3-SNAPSHOT
		minecraft: Minecraft 1.17.1
		net_dv8tion_jda: JDA 4.2.1_253
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_jetbrains_annotations: annotations 16.0.1
		org_yaml_snakeyaml: snakeyaml 1.29
		placeholder-api: Fabric Placeholder API 1.0.0-rc2-1.17
		recipecache: recipecache 0.2.0-1.17.1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		styledplayerlist: Styled Player List 2.1.0
		viabackwards: ViaBackwards 4.0.1
		viafabric: ViaFabric 0.4.3+203-main
		viafabric-mc117: ViaFabric for 1.17 0.4.3+203-main
		viarewind: ViaRewind 2.0.1
		viaversion: ViaVersion 4.0.1
	Player Count: 3 / 26111; [class_3222['IWannaNewName'/67318, l='ServerLevel[IdeaSpace Anarchy]', x=-5209745.34, y=64.00, z=-4689989.72], class_3222['tobfos'/181289, l='ServerLevel[IdeaSpace Anarchy]', x=-5209887.01, y=71.00, z=-4690025.11], class_3222['.tobfos'/184141, l='ServerLevel[IdeaSpace Anarchy]', x=-234.77, y=70.00, z=-193.84]]
	Data Packs: vanilla, file/CavesAndCliffsPreview.zip, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Camotoy** [comment] 2021-07-23 12:23
Tobfos, that is a Floodgate error that should be fixed. Please ensure you are updated.

**Comment by Camotoy** [comment] 2021-07-23 12:56
Closing as this should be fixed with the latest Floodgate-Fabric.

**Closed** 2021-07-23 12:55 UTC
Labels: Unconfirmed Bug
